version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: joshua-gulizia-portfolio
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
